### ISSUE TITLE
Biggest bottleneck?

### ISSUE THREAD

**Issue by Sven-vh** [takunology/MinecraftConnection#27]
Hi, first thing I want to say is thank you for making this. This library is everything I ever wanted. Super simple and does not limit you in any way.

There are a couple of things I would like to know. And it's mainly about speed.
What can be the biggest bottleneck? I'm making Conway's game of Life in Minecraft and when trying to do a 100x100 grid, it starts to get slow. When I run it in the C# console it's pretty fast. Is it the library that can only send x amount of commands to the server? Is it the server that can only receive x amount of requests? Is there a setting I can change in my server properties to increase the speed?

Also would multithreading my application work? Or would the server still only receive x amount of requests per second? 
(I'm sorry if this is the wrong place to ask this, I tried to mark this as a question but can't seem to find it)

**Comment by takunology** [comment]
Hi, sorry for the late reply.

As for the speed of command execution, it depends on the server specs. However, the fastest we have seen to execute commands on Minecraft is 50 milliseconds. The server executes commands one at a time, so even with asynchronous execution, there will be a wait for the command to execute. Therefore, no matter how high the server specs are, it cannot execute commands faster than 50 milliseconds, so the limit is 20 commands per second.
(This may be solved by using a mod, but we have not tested it with a mod, so we do not know if this library will work correctly.)

Asynchronous processing is essential for application development, but I have not yet gotten to that point. If you need asynchronous processing, we recommend using the [CoreRCON](https://github.com/Challengermode/CoreRcon) library instead of this library.

I am using a translation tool, so sorry if there are any wrong translations.
